### ISSUE TITLE
Blacklight 7 json is different.  Maps needs to be fixed

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/discoveryutils#133]
I noticed that the pulmap content is producing a 500 error in the discoveryutils app in staging

https://library-staging.princeton.edu/find/all/van%20gogh#catalog_block-catalog_pulmap_results
https://library-staging.princeton.edu/utils/mapsearch/any?query=van%20gogh&sid=library-main
Yeah the json structure seems to have changed quite substantially
https://maps.princeton.edu/catalog.json?utf8=%E2%9C%93&search_field=all_fields&q=cats

**Comment by carolyncole** [comment]
This is blocked by https://github.com/pulibrary/pulmap/issues/784

**Comment by eliotjordan** [comment]
These if statements should probably be removed:

https://github.com/pulibrary/discoveryutils/blob/master/classes/Blacklight/PulmapResponse.php#L27
https://github.com/pulibrary/discoveryutils/blob/master/classes/Blacklight/PulmapResponse.php#L30

These are specific to Orangelight. You can just set `author` and `publisher` directly.

Also, `url` should come from the `links` property.
https://github.com/pulibrary/discoveryutils/blob/master/classes/Blacklight/PulmapResponse.php#L37

**Comment by eliotjordan** [comment]
@carolyncole This is no longer blocked. Pulmap index view JSON has been updated:

https://maps.princeton.edu/catalog.json/?q=cats

**Comment by eliotjordan** [comment]
💯
