### ISSUE TITLE
ENVIRONMENT Variables not readable from app_configs directory

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/discoveryutils#138]
PHP applications are owned by the www-data user by default. We are loading the app's environment variables into the deploy users environment. This causes references to the $_ENV to produce errors like ```Notice: Undefined index: SUMMON_AUTHCODE``` when the app is run in staging or production.

**Comment by carolyncole** [comment]
@kevinreiss is this still an issue?  Both staging and production seem to be returning data.

**Comment by kevinreiss** [comment]
We are good here. Thanks.
