### ISSUE TITLE
Search by ISSN and "Any" search bring back the same results when checking Orangelight

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/discoveryutils#140]
https://library.princeton.edu/utils/pulsearch/any?query=0044-5975+OR+00445975&referrer=umlaut&limit=contains

https://library.princeton.edu/utils/pulsearch/issn?query=0044-5975+OR+00445975&referrer=umlaut&limit=contains

This was generated by the getit citation matching service. Example that produced the above ISSN set https://getit.princeton.edu/go/30073. The getit menu uses either the isbn or issn search scoping to try and get only "exact" matches.

**Comment by carolyncole** [comment]
It looks like we need two separate queries vs what we are sending which is one.  These two queries both return 4 results:
https://catalog.princeton.edu/catalog?q=00445975&search_field=issn&format=json&per_page=5 and combine that with https://catalog.princeton.edu/catalog?q=0044-5975&search_field=issn&format=json&per_page=5

This query returns thousands: https://catalog.princeton.edu/catalog?q=00445975+OR+0044-5975&search_field=issn&format=json&per_page=5

**Comment by carolyncole** [comment]
@kevinreiss is there a way to change the code sending the query, or would it be easier for discovery utils to parse the query and look for an OR?  And send the second set only if there are not enough results from the first?

**Comment by kevinreiss** [comment]
I think the best thing would be is to have the application stop passing the OR query with the normalized and "display" version of the standard number. I chatted a little bit with @tampakis about how OL handles these and I think just sending the normalized will be sufficient. It's a quick fix in the application  repo https://github.com/pulibrary/pulgetit that is making these requests.

**Comment by kevinreiss** [comment]
This fix was actually put in place on getit as discussed in the previous comment.
