### ISSUE TITLE
Search box in libguides header is broken

### ISSUE THREAD

**Issue by axamei** [pulibrary/discoveryutils#148]
The libguides search box tries to use the discovery utils with the following path, but gets error instead.

https://library.princeton.edu/utils/search/coreall?query=cats&op=Search&sid=libguides

<img width="1680" alt="Screen Shot 2019-11-19 at 9 29 21 AM" src="https://user-images.githubusercontent.com/8161144/69157897-972db400-0ab3-11ea-8ae8-eb9c3518d071.png">

**Comment by axamei** [comment]
@kevinreiss should we restore this? https://github.com/pulibrary/discoveryutils/commit/a81bf19f2e36f6febb7ce1bc2126537e96458d9b#diff-9ed0179a1554044884675891d93dadbbL228-L229

**Comment by kevinreiss** [comment]
Yes, we need to restore and upgrade this to work with Symfony.

**Comment by axamei** [comment]
Resolved.
