### ISSUE TITLE
Result number value for articles does not match up to results in Articles+

### ISSUE THREAD

**Issue by axamei** [pulibrary/discoveryutils#156]
We received a ticket (see below) about the result number values in the skip to section links not matching up with the actual result in the summon interface. 

>I'm having an issue with the Articles+ search. It seems
that the search is not showing the all the results that it populates for my
searches, or is otherwise misrepresenting the results. I keep getting it to
tell me I have over 200 returns on my search, but then only listing one or no
articles.

**Comment by kevinreiss** [comment]
the numbers are always different as far as I can tell. We don't display the count but it is displayed in a mouseover.
