### ISSUE TITLE
Quotes in Articles+ search do not work

### ISSUE THREAD

**Issue by axamei** [pulibrary/discoveryutils#158]
Refs https://github.com/pulibrary/pul_library_drupal/issues/1641

> Reported by Jeremy Darrington, confirmed this is an issue. Suspect it may be an encoding issue with either a recent release of the panels module or an issue within discoveryutils. Example:
> 
> Searches using quotation marks no longer return results no longer return results from Articles+ (nor, it appears, from the Catalog). See https://library.princeton.edu/find/all/%22Political%20order%20and%20political%20decay%22 vs. https://library.princeton.edu/find/all/Political%20order%20and%20political%20decay

it looks like an articles+ issue with the quotes. i did a search for “policy” and it led me to https://princeton.summon.serialssolutions.com/search?s.q=%26quot%3Bpolicy%26quot%3B&s.fvf=IsScholarly,true&keep_r=true&s.dym=t&s.ho=t#!/search?ho=t&fvf=IsScholarly,true,f&l=en&q=%26quot;policy%26quot;&dym=t. it’s changing the `"` to `&quot;`

See: https://library.princeton.edu/utils/articles/any?query=%22policy%22&sid=library-main-summon
`"query": "&amp;quot;policy&amp;quot;",`

**Comment by kevinreiss** [comment]
Fixed in July.
