### ISSUE TITLE
Empty publication date in articles search produces 500 error

### ISSUE THREAD

**Issue by axamei** [pulibrary/discoveryutils#176]
https://library.princeton.edu/utils/articles/any?query=The%20Psychology%20of%20Social%20Status&sid=library-main-summon

Produces a 500 error

**Comment by kevinreiss** [comment]
https://github.com/pulibrary/discoveryutils/blob/main/classes/Summon/Response.php#L43 is an example of where I think we need some better error handling, see comment on #177.
