### ISSUE TITLE
DPUL responds with a 500 of Undefined index: readonly_format_tesim

### ISSUE THREAD

**Issue by axamei** [pulibrary/discoveryutils#177]
https://library.princeton.edu/utils/dpulsearch/any?query=The%20Human%20Group&sid=library-main

**Comment by kevinreiss** [comment]
We probably want to route every potential attribute we look for through a method that handles undefined index and and "Trying to access array offset on value of type null". See https://github.com/pulibrary/discoveryutils/issues/176.
