### ISSUE TITLE
Articles Search Encoding Issue

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/discoveryutils#187]
When supplied turkish characters the search results display incorrectly

https://library.princeton.edu/find/all/%D8%AF%D9%8A%D9%86%20%D8%A7%D9%84%D8%B9%D8%B1%D8%A7%D9%82

I think this is an encoding issue we need to address on the articles plus side. Reported by staff yesterday via libanswers so I believe this is a relatively new issue.

**Comment by kevinreiss** [comment]
summon search api we are using: http://localhost:4000/bibliographic/1769972/holdings/2032939/availability.json

this is the client class that talks to the api: https://github.com/pulibrary/discoveryutils/blob/main/classes/Summon/Summon.php

**Comment by sdellis** [comment]
@kevinreiss What app is the localhost:4000 running in your above example?

**Comment by kevinreiss** [comment]
I pasted the wrong URL.
