### ISSUE TITLE
Articles 500 error: Undefined index: StartPage

### ISSUE THREAD

**Issue by axamei** [pulibrary/discoveryutils#192]
https://library.princeton.edu/utils/articles/any?query=Numerical%20modelling%20of%20Ar%20glow%20discharge%20at%20intermediate%20and%20high%20pressures&sid=library-main-summon

**Comment by sdellis** [comment]
@kevinreiss I think this has already bee fixed because the link above doesn't throw an error. I think the missing StartPage issue is addressed here: https://github.com/pulibrary/discoveryutils/blob/main/classes/Summon/Record.php#L51-L66
