### ISSUE TITLE
Refactor online availability/display to use electronic_portfolio_s when present

### ISSUE THREAD

**Issue by axamei** [pulibrary/discoveryutils#193]
Use `electronic_portfolio_s` instead of `electronic_access_1display`

Examples:

https://catalog-alma-qa.princeton.edu/catalog/9999635643506421/raw
https://catalog-alma-qa.princeton.edu/catalog/99122426947506421/raw

**Comment by kevinreiss** [comment]
both keys are now available in the solr response from Blacklight
