### ISSUE TITLE
Operation timeouts from the catalog

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/discoveryutils#210]
I'm seeing a lot of 500 errors in datadog which sometimes work just fine when I try them again.  They must be timeouts, which either work or do not...
![Screen Shot 2022-03-01 at 2 54 32 PM](https://user-images.githubusercontent.com/1599081/156239063-ffeafaa7-fb0c-4ace-aa84-3bfdf07969a1.png)

**Comment by kevinreiss** [comment]
I found same the pattern, good searches work sometimes but timeout otherwise.
